spring.application.name=vhn-global
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8080}
storage.base-path=uploads
storage.image-path=${storage.base-path}/images
storage.image-serve-path=file:./${storage.image-path}/
storage.image-handler=/images/**
image.base-url=${IMAGE_BASE_URL:http://localhost:8080}/images/
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.web.servlet.resource=ERROR
jwt.secret-key=${JWT_SECRET_KEY:wH0Hzn1vj0CBB8+qYUYz7VSpO9B7r8FeRXGeYlD6ysM=}
security.enabled=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,application/json